blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ï¸ Ask question
    url: https://github.com/CarbonPackages/Carbon.TailwindSpacing/discussions/new/choose
    about: Please ask and answer questions in discussions
